### ISSUE TITLE
Piz add node_modules back

### ISSUE THREAD

**Issue by herruth45** [FilippoCesana/FancyGallery#4]
I can not compyling anymore. Plz put it back

**Comment by thefooly** [comment]
node_modules should not be added to the repo

**Comment by herruth45** [comment]
Why sir? I can not compyling now

**Comment by thefooly** [comment]
Because node_modules are the dependencies of your project and are described in your package.json file. When you pull or checkout the project you should reinstall them in your machine by running either the command ```yarn install``` or ```npm install``` in your root folder.

**Comment by herruth45** [comment]
Thank you sir.
Kthxbye
